#!/usr/bin/env node
/**
 * Fake SAML IdP launcher for local SSO testing.
 *
 * - Generates a self-signed cert + key on first run (gitignored)
 * - Spawns `saml-idp` configured for our /api/auth/saml/callback
 * - Prints the exact values to paste into /super-admin/settings/sso
 *
 * Env vars (all optional):
 *   APP_URL          App base URL (default http://localhost:3000)
 *   IDP_PORT         Port for the IdP (default 7000)
 *   IDP_TEST_EMAIL   Default NameID for sign-in (default charity-admin@example.com)
 */

import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import selfsigned from 'selfsigned'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const APP_URL = (process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, '')
const ACS_URL = `${APP_URL}/api/auth/saml/callback`
const IDP_PORT = Number(process.env.IDP_PORT || 7000)
const IDP_BASE = `http://localhost:${IDP_PORT}`
const IDP_ISSUER = `${IDP_BASE}/metadata`
const SSO_URL = `${IDP_BASE}/saml/sso`
const TEST_EMAIL = process.env.IDP_TEST_EMAIL || 'charity-admin@example.com'

const certPath = join(__dirname, 'cert.pem')
const keyPath = join(__dirname, 'key.pem')

if (!existsSync(certPath) || !existsSync(keyPath)) {
  console.log('🔐  Generating self-signed cert for fake IdP (one-time)…')
  mkdirSync(__dirname, { recursive: true })
  // selfsigned >=3 is async and uses { keySize } / { algorithm: 'sha256' }.
  const pems = await selfsigned.generate(
    [{ name: 'commonName', value: 'fake-saml-idp' }],
    { days: 365, keySize: 2048, algorithm: 'sha256' }
  )
  if (!pems?.cert || !pems?.private) {
    throw new Error('selfsigned.generate returned no cert/private — check selfsigned version')
  }
  writeFileSync(certPath, pems.cert, 'utf-8')
  writeFileSync(keyPath, pems.private, 'utf-8')
  console.log('    ✅  Cert + key written to scripts/fake-saml-idp/\n')
}

const cert = readFileSync(certPath, 'utf-8').trim()

const banner = `
═══════════════════════════════════════════════════════════════════════
  Fake SAML IdP — paste these into /super-admin/settings/sso
═══════════════════════════════════════════════════════════════════════

  Display Name:   Fake Charity SSO   (or any label you like)
  Entity ID:      ${IDP_ISSUER}
  SSO URL:        ${SSO_URL}
  Certificate:

${cert}

  ──────────────────────────────────────────────────────────────────────
  Default test user (NameID returned in the assertion):
    ${TEST_EMAIL}

  → that user must already exist in the DB as SUPER_ADMIN or
    CHARITY_EMPLOYEE for the callback to mint a session.
    Easy options:
      • Use your existing super-admin email — change ${TEST_EMAIL}
        on the IdP login form before clicking "Sign in", OR
      • Set IDP_TEST_EMAIL=you@example.com when starting the IdP.

  Leave "Enforce SSO for charity users" OFF until you've confirmed
  end-to-end login works — otherwise you can lock yourself out of
  password login as a charity admin.

  ──────────────────────────────────────────────────────────────────────
  Test flow:
    1. Save SSO config in /super-admin/settings/sso
    2. Sign out
    3. On /login click "Single Sign-On" tab → enter charity email
       (or click "Charity sign-in" entry point if your UI has one)
    4. Browser redirects here → click "Sign in" on the IdP page
    5. Browser POSTs back to ${ACS_URL}
    6. You land on / signed in via SAML

═══════════════════════════════════════════════════════════════════════
`
console.log(banner)

// saml-idp `--configFile` expects a JS module exporting `{ user, metadata }`.
// Always overwrite so changes to IDP_TEST_EMAIL take effect on next start.
const idpConfigPath = join(__dirname, 'idp-config.js')
writeFileSync(
  idpConfigPath,
  `// Auto-generated by scripts/fake-saml-idp/start.mjs — do not edit by hand.
module.exports = {
  user: {
    userName: ${JSON.stringify(TEST_EMAIL)},
    nameIDFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    nameID: ${JSON.stringify(TEST_EMAIL)},
    email: ${JSON.stringify(TEST_EMAIL)},
    displayName: 'Charity Admin (fake)',
    firstName: 'Charity',
    lastName: 'Admin',
  },
  metadata: [
    { id: 'firstName',   optional: true,  displayName: 'First Name',   description: '',  multiValue: false },
    { id: 'lastName',    optional: true,  displayName: 'Last Name',    description: '',  multiValue: false },
    { id: 'displayName', optional: true,  displayName: 'Display Name', description: '',  multiValue: false },
    { id: 'email',       optional: false, displayName: 'E-Mail',       description: '',  multiValue: false },
  ],
}
`,
  'utf-8'
)

const args = [
  'saml-idp',
  '--acsUrl', ACS_URL,
  '--audience', APP_URL,
  '--issuer', IDP_ISSUER,
  '--cert', certPath,
  '--key', keyPath,
  '--port', String(IDP_PORT),
  '--configFile', idpConfigPath,
]

console.log(`🚀  Starting fake IdP on ${IDP_BASE}\n`)

const child = spawn('npx', args, {
  stdio: 'inherit',
  shell: true,
  env: { ...process.env },
})
child.on('exit', (code) => process.exit(code ?? 0))
